import React, { useState, useEffect, useMemo } from 'react';
import {
  RefreshCw, Search, Download, AlertCircle, Sparkles, ChevronUp, ChevronDown,
  ChevronRight, Calendar, TrendingUp, DollarSign, Users, BarChart2
} from 'lucide-react';
import supabase from '../lib/supabase';
import {
  formatCurrency, formatDate, formatDateLong, formatDateFilename,
  getDateRangeByFilter, calculateIncomeSummary, generateBusinessInsights
} from '../lib/utils';

// ── PDF Export ───────────────────────────────────────────────────
async function exportPDF(filteredRows, label, summary) {
  const { default: jsPDF }      = await import('jspdf');
  const { default: autoTable  } = await import('jspdf-autotable');

  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' });

  // Header
  doc.setFontSize(16);
  doc.setTextColor(212, 175, 55);
  doc.text('ETERNAL MYTH STUDIO', 40, 40);
  doc.setFontSize(11);
  doc.setTextColor(180, 180, 180);
  doc.text('Payout Community — Income Report', 40, 58);

  // Period
  doc.setFontSize(9);
  doc.setTextColor(220, 220, 220);
  doc.text(`Periode: ${label}`, 40, 76);
  doc.text(`Diekspor: ${formatDateLong(new Date().toISOString())}`, 40, 90);

  // Summary box
  const sumY = 105;
  doc.setFontSize(9);
  doc.setTextColor(140, 140, 140);
  const summaryLines = [
    `Total Transaksi: ${summary.completedCount}`,
    `Total Robux Terjual: ${summary.totalRobux.toLocaleString('id-ID')}`,
    `Total Pemasukan: ${formatCurrency(summary.totalRevenue)}`,
    `Rata-rata Transaksi: ${formatCurrency(Math.round(summary.avgTx))}`,
    `Staff: ${summary.staffCount}   Pembelian Pertama: ${summary.firstBuyCount}   Normal: ${summary.normalCount}`,
  ];
  summaryLines.forEach((line, i) => {
    doc.text(line, 40, sumY + i * 14);
  });

  // Table
  const tableStart = sumY + summaryLines.length * 14 + 14;
  autoTable(doc, {
    startY: tableStart,
    head: [['No', 'Tanggal', 'Order Code', 'Username', 'Display Name', 'Robux', 'Kategori', 'Harga/Robux', 'Total Harga']],
    body: filteredRows.map((row, i) => [
      i + 1,
      formatDate(row.completed_at || row.created_at, { dateStyle: 'short' }),
      row.order_code,
      row.roblox_username,
      row.display_name,
      (row.robux_amount || 0).toLocaleString('id-ID'),
      row.category,
      formatCurrency(row.price_per_robux),
      formatCurrency(row.total_price)
    ]),
    styles: { fontSize: 8, cellPadding: 4 },
    headStyles: { fillColor: [30, 25, 10], textColor: [212, 175, 55], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [18, 18, 22] },
    bodyStyles: { textColor: [220, 220, 220] }
  });

  // Footer
  const pageH = doc.internal.pageSize.height;
  doc.setFontSize(7);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by EMS Portal — Eternal Myth Studio', 40, pageH - 20);

  // File name
  const today = new Date();
  const suffix = formatDateFilename(today);
  doc.save(`ems-income-report-${suffix}.pdf`);
}

// ── Filter Presets Config ─────────────────────────────────────────
const FILTER_PRESETS = [
  { key: 'today',     label: 'Hari Ini' },
  { key: '7days',     label: '7 Hari Terakhir' },
  { key: 'thisMonth', label: 'Bulan Ini' },
  { key: 'thisYear',  label: 'Tahun Ini' },
  { key: 'pickMonth', label: 'Pilih Bulan' },
  { key: 'pickDate',  label: 'Pilih Tanggal' },
  { key: 'custom',    label: 'Custom Range' }
];

// ── Sortable Column Header ────────────────────────────────────────
function SortTh({ label, field, sortField, sortOrder, onSort }) {
  const active = sortField === field;
  return (
    <th
      className="py-4 px-4 cursor-pointer select-none whitespace-nowrap group"
      onClick={() => onSort(field)}
    >
      <div className="flex items-center gap-1">
        <span>{label}</span>
        <span className={`transition-opacity ${active ? 'opacity-100' : 'opacity-0 group-hover:opacity-50'}`}>
          {active && sortOrder === 'asc' ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
        </span>
      </div>
    </th>
  );
}

// ── Main Component ────────────────────────────────────────────────
export default function AdminIncome() {
  const [allCompleted, setAllCompleted] = useState([]);
  const [pendingTx,    setPendingTx]    = useState([]);
  const [cancelledTx,  setCancelledTx]  = useState([]);
  const [loading, setLoading]           = useState(true);
  const [error,   setError]             = useState(null);

  // Filters
  const [filterKey,     setFilterKey]     = useState('thisMonth');
  const [customStart,   setCustomStart]   = useState('');
  const [customEnd,     setCustomEnd]     = useState('');
  const [selectedMonth, setSelectedMonth] = useState(() => {
    const now = new Date();
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  });
  const [selectedDate, setSelectedDate]   = useState(() => new Date().toISOString().slice(0, 10));

  // Search & Sort
  const [search,    setSearch]    = useState('');
  const [sortField, setSortField] = useState('completed_at');
  const [sortOrder, setSortOrder] = useState('desc');

  // ── Fetch ────────────────────────────────────────────────────────
  const fetchData = async () => {
    setLoading(true);
    setError(null);
    try {
      const { data, error: err } = await supabase
        .from('transactions')
        .select('*')
        .order('created_at', { ascending: false });
      if (err) throw err;
      const txs = data || [];
      setAllCompleted(txs.filter(t => t.admin_status === 'completed'));
      setPendingTx(   txs.filter(t => t.admin_status === 'pending'));
      setCancelledTx( txs.filter(t => t.admin_status === 'cancelled'));
    } catch (err) {
      console.error('AdminIncome fetch error:', err);
      setError('Gagal memuat data pemasukan.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchData(); }, []);

  // ── Derived date range ───────────────────────────────────────────
  const { start, end, label } = useMemo(
    () => getDateRangeByFilter(filterKey, customStart, customEnd, selectedMonth, selectedDate),
    [filterKey, customStart, customEnd, selectedMonth, selectedDate]
  );

  // ── Filtered rows ────────────────────────────────────────────────
  const filteredRows = useMemo(() => {
    let rows = allCompleted;

    // Date filter
    if (start && end) {
      rows = rows.filter(t => {
        const d = new Date(t.completed_at || t.created_at);
        return d >= start && d <= end;
      });
    }

    // Search
    if (search.trim()) {
      const q = search.toLowerCase();
      rows = rows.filter(t =>
        t.roblox_username?.toLowerCase().includes(q) ||
        t.display_name?.toLowerCase().includes(q) ||
        t.order_code?.toLowerCase().includes(q)
      );
    }

    // Sort
    rows = [...rows].sort((a, b) => {
      let aVal, bVal;
      switch (sortField) {
        case 'completed_at': aVal = new Date(a.completed_at || a.created_at); bVal = new Date(b.completed_at || b.created_at); break;
        case 'total_price':  aVal = a.total_price  || 0; bVal = b.total_price  || 0; break;
        case 'robux_amount': aVal = a.robux_amount || 0; bVal = b.robux_amount || 0; break;
        default:             aVal = a[sortField] || ''; bVal = b[sortField] || '';
      }
      if (aVal < bVal) return sortOrder === 'asc' ? -1 : 1;
      if (aVal > bVal) return sortOrder === 'asc' ?  1 : -1;
      return 0;
    });

    return rows;
  }, [allCompleted, start, end, search, sortField, sortOrder]);

  const summary  = useMemo(() => calculateIncomeSummary(filteredRows), [filteredRows]);
  const insights = useMemo(
    () => generateBusinessInsights(filteredRows, pendingTx, cancelledTx),
    [filteredRows, pendingTx, cancelledTx]
  );

  const handleSort = (field) => {
    if (sortField === field) setSortOrder(o => o === 'asc' ? 'desc' : 'asc');
    else { setSortField(field); setSortOrder('desc'); }
  };

  const insightTypeStyle = (type) => {
    if (type === 'warning')        return 'text-yellow-300';
    if (type === 'recommendation') return 'text-gold-light';
    return 'text-slate-300';
  };

  const categoryStyle = (c) => {
    if (c === 'Staff')             return 'text-sky-400';
    if (c === 'Pembelian Pertama') return 'text-emerald-400';
    return 'text-gold-light';
  };

  // ── Render ───────────────────────────────────────────────────────
  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-obsidian-border/50 pb-4">
        <div>
          <h2 className="font-fantasy text-2xl font-bold tracking-wide text-glow-gold text-gold-light uppercase">Pemasukan</h2>
          <p className="text-xs text-slate-400 mt-1">Laporan transaksi selesai (admin_status = completed)</p>
        </div>
        <div className="flex gap-2">
          <button onClick={fetchData} className="btn-premium-dark p-2.5 rounded-lg flex items-center gap-1.5 text-xs cursor-pointer font-bold">
            <RefreshCw className="w-3.5 h-3.5" />
            <span>Refresh</span>
          </button>
          <button
            onClick={() => exportPDF(filteredRows, label, summary)}
            disabled={filteredRows.length === 0}
            className="btn-premium-gold px-4 py-2.5 rounded-lg flex items-center gap-1.5 text-xs cursor-pointer font-bold disabled:opacity-40 disabled:cursor-not-allowed"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export PDF</span>
          </button>
        </div>
      </div>

      {error && (
        <div className="bg-red-500/10 border border-red-500/20 rounded-xl p-4 flex items-start gap-2.5 text-xs text-crimson-light">
          <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
          <span className="font-semibold">{error}</span>
        </div>
      )}

      {/* Filter Presets */}
      <div className="space-y-3">
        <div className="flex flex-wrap gap-2">
          {FILTER_PRESETS.map(p => (
            <button
              key={p.key}
              onClick={() => setFilterKey(p.key)}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold border transition-all duration-200 cursor-pointer ${
                filterKey === p.key
                  ? 'bg-gold-primary/15 border-gold-primary text-gold-light'
                  : 'border-obsidian-border text-slate-400 hover:border-gold-dark hover:text-slate-200'
              }`}
            >
              {p.label}
            </button>
          ))}
        </div>

        {/* Dynamic picker */}
        {filterKey === 'pickMonth' && (
          <div className="flex items-center gap-2">
            <Calendar className="w-4 h-4 text-gold-dark" />
            <input type="month" value={selectedMonth} onChange={e => setSelectedMonth(e.target.value)}
              className="bg-obsidian-900 border border-obsidian-border text-slate-200 text-xs rounded-lg px-3 py-2 focus:outline-none focus:border-gold-primary" />
          </div>
        )}
        {filterKey === 'pickDate' && (
          <div className="flex items-center gap-2">
            <Calendar className="w-4 h-4 text-gold-dark" />
            <input type="date" value={selectedDate} max={new Date().toISOString().slice(0, 10)}
              onChange={e => setSelectedDate(e.target.value)}
              className="bg-obsidian-900 border border-obsidian-border text-slate-200 text-xs rounded-lg px-3 py-2 focus:outline-none focus:border-gold-primary" />
          </div>
        )}
        {filterKey === 'custom' && (
          <div className="flex flex-wrap items-center gap-3">
            <div className="flex items-center gap-2">
              <span className="text-xs text-slate-400 font-semibold">Dari:</span>
              <input type="date" value={customStart} max={customEnd || new Date().toISOString().slice(0, 10)}
                onChange={e => setCustomStart(e.target.value)}
                className="bg-obsidian-900 border border-obsidian-border text-slate-200 text-xs rounded-lg px-3 py-2 focus:outline-none focus:border-gold-primary" />
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xs text-slate-400 font-semibold">Sampai:</span>
              <input type="date" value={customEnd} min={customStart} max={new Date().toISOString().slice(0, 10)}
                onChange={e => setCustomEnd(e.target.value)}
                className="bg-obsidian-900 border border-obsidian-border text-slate-200 text-xs rounded-lg px-3 py-2 focus:outline-none focus:border-gold-primary" />
            </div>
          </div>
        )}

        {label !== '-' && (
          <p className="text-[11px] text-gold-dark font-semibold">Menampilkan: <span className="text-gold-light">{label}</span></p>
        )}
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
        {[
          { icon: BarChart2,  label: 'Total Transaksi',       value: summary.completedCount,                            color: 'text-slate-200' },
          { icon: DollarSign, label: 'Total Pemasukan',        value: formatCurrency(summary.totalRevenue),              color: 'text-gold-light' },
          { icon: TrendingUp, label: 'Total Robux Terjual',    value: `${summary.totalRobux.toLocaleString('id-ID')} R$`,color: 'text-sky-400' },
          { icon: DollarSign, label: 'Rata-rata Transaksi',    value: formatCurrency(Math.round(summary.avgTx)),         color: 'text-emerald-400' },
          { icon: Users,      label: 'Transaksi Staff',        value: summary.staffCount,                                color: 'text-sky-400' },
          { icon: Users,      label: 'Pembelian Pertama',      value: summary.firstBuyCount,                             color: 'text-emerald-400' },
          { icon: Users,      label: 'Normal (Repeat)',         value: summary.normalCount,                               color: 'text-gold-light' },
        ].map((item, i) => {
          const Icon = item.icon;
          return (
            <div key={i} className="glass-panel p-4 rounded-xl border border-obsidian-border/40 flex flex-col gap-1">
              <div className="flex items-center gap-1.5">
                <Icon className="w-3.5 h-3.5 text-gold-dark" />
                <span className="text-[10px] uppercase font-bold tracking-wider text-slate-500">{item.label}</span>
              </div>
              <span className={`text-xl font-black ${item.color}`}>{item.value}</span>
            </div>
          );
        })}
      </div>

      {/* Search */}
      <div className="relative rounded-lg overflow-hidden border border-obsidian-border bg-obsidian-900 focus-within:border-gold-primary transition-all duration-300 max-w-md">
        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <Search className="h-4 w-4 text-slate-500" />
        </div>
        <input
          type="text"
          placeholder="Cari username, display name, atau kode order..."
          value={search}
          onChange={e => setSearch(e.target.value)}
          className="block w-full pl-10 pr-3 py-2.5 bg-transparent text-slate-100 placeholder-slate-600 focus:outline-none text-xs font-semibold"
        />
      </div>

      {/* Table */}
      {loading ? (
        <div className="h-48 flex items-center justify-center flex-col gap-3">
          <RefreshCw className="w-7 h-7 text-gold-primary animate-spin" />
          <span className="text-xs text-slate-400 animate-pulse">Memuat data pemasukan...</span>
        </div>
      ) : filteredRows.length === 0 ? (
        <div className="glass-panel p-12 text-center rounded-2xl border border-obsidian-border/50 text-slate-400 text-sm">
          Belum ada transaksi selesai pada periode ini.
        </div>
      ) : (
        <div className="glass-panel rounded-2xl border border-obsidian-border/50 overflow-hidden">
          <div className="overflow-x-auto w-full">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="bg-obsidian-950/80 border-b border-obsidian-border/50 text-gold-dark font-bold uppercase tracking-wider text-[10px]">
                  <th className="py-4 px-4">#</th>
                  <SortTh label="Tanggal"    field="completed_at"  sortField={sortField} sortOrder={sortOrder} onSort={handleSort} />
                  <th className="py-4 px-4">Order Code</th>
                  <SortTh label="Username"   field="roblox_username" sortField={sortField} sortOrder={sortOrder} onSort={handleSort} />
                  <th className="py-4 px-4">Display Name</th>
                  <SortTh label="Robux"      field="robux_amount"  sortField={sortField} sortOrder={sortOrder} onSort={handleSort} />
                  <th className="py-4 px-4">Kategori</th>
                  <th className="py-4 px-4">Harga/Robux</th>
                  <SortTh label="Total Harga" field="total_price"  sortField={sortField} sortOrder={sortOrder} onSort={handleSort} />
                  <th className="py-4 px-4">Catatan</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-obsidian-border/30">
                {filteredRows.map((row, i) => (
                  <tr key={row.id} className="hover:bg-obsidian-900/30 transition-colors">
                    <td className="py-3 px-4 text-slate-500 font-medium">{i + 1}</td>
                    <td className="py-3 px-4 text-slate-400 whitespace-nowrap">{formatDate(row.completed_at || row.created_at, { dateStyle: 'short', timeStyle: 'short' })}</td>
                    <td className="py-3 px-4 font-mono font-bold text-slate-100 whitespace-nowrap">{row.order_code}</td>
                    <td className="py-3 px-4 font-semibold text-slate-200">{row.roblox_username}</td>
                    <td className="py-3 px-4 text-slate-400">{row.display_name}</td>
                    <td className="py-3 px-4 font-bold text-slate-200">{(row.robux_amount || 0).toLocaleString('id-ID')}</td>
                    <td className={`py-3 px-4 font-semibold ${categoryStyle(row.category)}`}>{row.category}</td>
                    <td className="py-3 px-4 text-slate-300">{formatCurrency(row.price_per_robux)}</td>
                    <td className="py-3 px-4 font-extrabold text-gold-light text-glow-gold whitespace-nowrap">{formatCurrency(row.total_price)}</td>
                    <td className="py-3 px-4 text-slate-500 max-w-[120px] truncate">{row.notes || '-'}</td>
                  </tr>
                ))}
              </tbody>
              <tfoot>
                <tr className="bg-obsidian-950/60 border-t border-obsidian-border/50">
                  <td colSpan={8} className="py-3 px-4 text-xs font-bold text-slate-400 uppercase tracking-wider">Total Pemasukan</td>
                  <td className="py-3 px-4 font-black text-gold-light text-glow-gold">{formatCurrency(summary.totalRevenue)}</td>
                  <td></td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      )}

      {/* AI Business Insight — Income Page (full) */}
      <div className="glass-panel p-6 rounded-2xl border border-gold-primary/20">
        <div className="flex items-center gap-2 mb-5 border-b border-obsidian-border/40 pb-3">
          <Sparkles className="w-4 h-4 text-gold-primary" />
          <h3 className="font-fantasy text-base font-bold text-gold-light tracking-wide">AI Business Insight</h3>
          <span className="ml-auto text-[9px] text-slate-600 font-semibold uppercase tracking-wider">Analisis berdasarkan filter aktif</span>
        </div>

        {insights.length === 0 ? (
          <p className="text-xs text-slate-500">Belum cukup data untuk menghasilkan insight.</p>
        ) : (
          <div className="space-y-3">
            {insights.map((item, i) => (
              <div key={i} className={`flex gap-2.5 items-start text-xs ${insightTypeStyle(item.type)}`}>
                <ChevronRight className="w-3.5 h-3.5 mt-0.5 shrink-0 text-gold-dark" />
                <div>
                  <span>{item.text}</span>
                  {item.items && (
                    <ul className="mt-1.5 space-y-1 pl-3">
                      {item.items.map((rec, j) => (
                        <li key={j} className="text-slate-400 list-disc list-inside">{rec}</li>
                      ))}
                    </ul>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
