// Data dummy generik untuk demo template ini.
// Silakan ganti nama produk, harga, kategori, dan gambar sesuai produk yang
// benar-benar kamu jual sebagai reseller.

export const dummyProducts = [
  {
    name: 'Hydra Glow Facial Serum',
    category: 'Skincare',
    price: 145000,
    discountPrice: 119000,
    description: 'Serum wajah dengan vitamin C untuk kulit tampak lebih cerah dan lembap.',
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600',
    status: 'Ready Stock',
  },
  {
    name: 'Velvet Matte Lip Cream',
    category: 'Makeup',
    price: 65000,
    discountPrice: null,
    description: 'Lip cream tekstur matte, tahan lama, tersedia 6 varian warna.',
    imageUrl: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600',
    status: 'Ready Stock',
  },
  {
    name: 'Aqua Fresh Eau de Parfum 50ml',
    category: 'Parfum',
    price: 210000,
    discountPrice: 185000,
    description: 'Aroma segar citrus-floral, cocok untuk penggunaan sehari-hari.',
    imageUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600',
    status: 'Ready Stock',
  },
  {
    name: 'Argan Repair Hair Serum',
    category: 'Hair Care',
    price: 89000,
    discountPrice: null,
    description: 'Serum rambut dengan argan oil untuk memperbaiki rambut kering & bercabang.',
    imageUrl: 'https://images.unsplash.com/photo-1626015365107-9fb35a6a4a0c?w=600',
    status: 'Ready Stock',
  },
  {
    name: 'Milk Body Lotion 400ml',
    category: 'Body Care',
    price: 78000,
    discountPrice: 65000,
    description: 'Lotion tubuh dengan susu & shea butter untuk kulit lembut seharian.',
    imageUrl: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600',
    status: 'Ready Stock',
  },
  {
    name: 'Overnight Repair Night Cream',
    category: 'Skincare',
    price: 135000,
    discountPrice: null,
    description: 'Krim malam untuk regenerasi kulit, mengandung niacinamide dan retinol ringan.',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600',
    status: 'Pre Order',
  },
  {
    name: 'Soft Focus Loose Powder',
    category: 'Makeup',
    price: 95000,
    discountPrice: 79000,
    description: 'Bedak tabur ringan dengan hasil akhir matte natural, cocok semua jenis kulit.',
    imageUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600',
    status: 'Ready Stock',
  },
  {
    name: 'Blossom Rose Eau de Toilette 30ml',
    category: 'Parfum',
    price: 98000,
    discountPrice: null,
    description: 'Parfum wangi bunga mawar lembut, ukuran travel-friendly.',
    imageUrl: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600',
    status: 'Ready Stock',
  },
  {
    name: 'Volumizing Shampoo 350ml',
    category: 'Hair Care',
    price: 72000,
    discountPrice: 60000,
    description: 'Shampo untuk menambah volume rambut tipis tanpa membuat lepek.',
    imageUrl: 'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=600',
    status: 'Ready Stock',
  },
  {
    name: 'Whitening Body Scrub 250g',
    category: 'Body Care',
    price: 55000,
    discountPrice: null,
    description: 'Scrub tubuh dengan ekstrak lemon untuk mengangkat sel kulit mati.',
    imageUrl: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=600',
    status: 'Ready Stock',
  },
]

export const dummyPromos = [
  {
    title: 'Diskon Skincare 20%',
    description: 'Berlaku untuk semua produk skincare selama bulan ini.',
    discount: 20,
    validUntil: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600',
    active: true,
  },
  {
    title: 'Bundling Makeup Hemat',
    description: 'Beli 2 produk makeup, gratis ongkir se-kota.',
    discount: 15,
    validUntil: new Date(new Date().setMonth(new Date().getMonth() + 1)).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=600',
    active: true,
  },
  {
    title: 'Promo Parfum Akhir Bulan',
    description: 'Diskon spesial untuk koleksi parfum pilihan.',
    discount: 10,
    validUntil: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600',
    active: false,
  },
]
